name: Build and Publish on Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Cross-Platform Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [osx-x64, osx-arm64, linux-x64, linux-arm64, win-x64, win-arm64]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Update as needed

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Publish the application
      - name: Publish for ${{ matrix.os }}
        run: dotnet publish -c Release -r ${{ matrix.os }} \
              /p:PublishSingleFile=true \
              /p:IncludeNativeLibrariesForSelfExtract=false \
              /p:PublishTrimmed=true \
              /p:TrimMode=Link \
              --self-contained true

      # Upload binaries as an artifact
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.os }}
          path: |
            **/bin/Release/net*/${{ matrix.os }}/publish/*

      # Attach binaries to the release
      - name: Upload binaries to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "**/bin/Release/net*/${{ matrix.os }}/publish/*"
          asset_name: binary-${{ matrix.os }}.zip
          asset_content_type: application/zip
