name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test on Multiple Platforms
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: ['9.0.x'] # Specify .NET version to test against

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Navigate to the tests folder
      - name: Change to tests folder
        run: cd tests

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./tests

      # Run tests
      - name: Run tests
        run: dotnet test ./tests --no-restore --verbosity normal
